project:
  name: ccoa
  regions:
    - us-east-1
tests:
  lesson1-sqs:
    template: ./lesson1-automation/ccoa-1-cfn.yml
  lesson1-pipeline:
    parameters:
      CodeCommitS3Bucket: S3_BUCKET_TOKEN
      CodeCommitS3Key: ccoa-1-examples.zip
      EmailAddress: fake-email@fake-fake-fake-email.com
    template: ./lesson1-automation/ccoa-1-pipeline.yml
  lesson2-cfn-nag:
    parameters:
      CodeCommitS3Bucket: S3_BUCKET_TOKEN
      CodeCommitS3Key: ccoa-2-examples.zip
    template: ./lesson2-preventive/ccoa-2-cfn-nag-pipeline.yml
  lesson3-config-rules-s3:
    template: ./lesson3-detective/ccoa-config-rules-s3.yml
  lesson5-remediation:
    template: ./lesson5-remediation/ccoa-5-ec2-eip-remediation.yml
  lesson6-continuous:
    parameters:
      CodeCommitS3Bucket: S3_BUCKET_TOKEN
      CodeCommitS3Key: ccoa-6-examples.zip
      CreateConfig: donotcreate
    template: ./lesson6-continuous/ccoa-6-pipeline.yml
