version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python --version
  pre_build:
    commands:
      - >-
        ls -las
      - chmod +x *.sh
      - ./update-taskcat.sh $PIPELINE_BUCKET
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - >-
        aws cloudformation create-stack --stack-name ccoa-cr --capabilities CAPABILITY_NAMED_IAM --disable-rollback --template-body file://lesson5-remediation/ccoa-5-config-recorder.yml
      - >-
        sleep 35
      - >-
        zip -r ccoa-1-examples.zip ./lesson1-automation -j -x '*.git*'
      - >-
        zip -r ccoa-2-examples.zip ./lesson2-preventive -j -x '*.git*'
      - >-
        zip -r ccoa-3-examples.zip ./lesson3-detective -j -x '*.git*'
      - >-
        zip -r ccoa-4-examples.zip ./lesson4-detective-more -j -x '*.git*'
      - >-
        zip -r ccoa-5-examples.zip ./lesson5-remediation -j -x '*.git*'
      - >-
        zip -r ccoa-6-examples.zip ./lesson6-continuous -j -x '*.git*'
      - >-
        aws s3 sync . s3://$PIPELINE_BUCKET
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'