version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      # - >-
      #   aws s3api list-buckets --query 'Buckets[?starts_with(Name,
      #   `ccoa-`) == `true`].[Name]' --output text | xargs -I {} aws s3
      #   rb s3://{} --force
      # - sleep 20
      # - 'aws s3 mb s3://ccoa-workshop'
      - 'aws s3 sync . s3://ccoa-workshop'
      - cd lesson0-setup
      - python ccoa-delete-config.py
      - cd ../lesson1-automation
      - zip ccoa-1-examples.zip *.*
      - 'aws s3 sync . s3://ccoa-workshop'
      - cd ../lesson2-preventive
      - zip ccoa-2-examples.zip *.*
      - 'aws s3 sync . s3://ccoa-workshop'
      - cd ../lesson5-remediation
      - zip ccoa-lesson5-examples.zip *.*
      - 'aws s3 sync . s3://ccoa-workshop'
      - cd ../lesson6-continuous
      - zip ccoa-6-examples.zip *.*
      - 'aws s3 sync . s3://ccoa-workshop'
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'