version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
          - echo "Installing Node.js version 12 ..."
          - n $NODE_12_VERSION
  build:
    commands:
      - npm install
      - npm install aws-cli-js
      - >-
        aws cloudformation package --template sam-s3-remediation.yml --s3-bucket
        $S3_BUCKET --output-template template-export.json
artifacts:
  type: zip
  files:
    - template-export.json
