---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stelligent CloudFormation Sample Template ** This template creates one
  or more Amazon resources. You will be billed for the AWS resources used if you create
  a stack from this template.
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub SampleQueue-${AWS::StackName}
Outputs:
  MyAWSAccountId:
    Value:
      Ref: AWS::AccountId
